name: Bug report
description: Create a report to help us improve
title: '[BUG] '
labels: ['bug']
assignees: ['esdrassantos06']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what happened...
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
      placeholder: You can upload images by clicking in this area and then dragging files in

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - Windows
        - macOS
        - Linux
        - iOS
        - Android
        - Other (specify in additional context)
    validations:
      required: true

  - type: input
    id: browser
    attributes:
      label: Browser/Version
      description: What browser and version are you using?
      placeholder: e.g., Chrome 91
    validations:
      required: true

  - type: input
    id: app-version
    attributes:
      label: App Version
      description: What version of our application are you running?
      placeholder: e.g., 1.0.2
    validations:
      required: true

  - type: checkboxes
    id: verification
    attributes:
      label: Verification
      description: Before submitting, please verify that you have completed the following
      options:
        - label: I have searched for similar bugs before creating this report
          required: true
        - label: I have included detailed steps to reproduce the issue
          required: true
        - label: I have included relevant environment information
          required: true
        - label: I have removed sensitive information from my submission

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
