name: Feature request
description: Suggest an idea for this project
title: '[FEATURE] '
labels: ['enhancement']
assignees: ['esdrassantos06']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature!

  - type: textarea
    id: problem-description
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is
      placeholder: I'm always frustrated when [...]
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false

  - type: checkboxes
    id: verification
    attributes:
      label: Before submitting
      description: Please verify that you have completed the following
      options:
        - label: I have searched for similar feature requests before creating this one
          required: true
        - label: This feature would benefit multiple users, not just my specific use case
          required: false
        - label: I've considered the scope and complexity of implementing this feature
          required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important do you consider this feature?
      options:
        - Critical (blocking my work)
        - High (significant improvement)
        - Medium (notable enhancement)
        - Low (would be nice to have)
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
