import type { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google";
import SessionProvider from "../components/SessionProvider"
import { getServerSession } from "next-auth";
import NavMenu  from '../components/NavMenu'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();

  return (
    <html lang="en" suppressHydrationWarning>
        <body suppressHydrationWarning className={`${inter.className}`}>
          <SessionProvider session={session}>
            <NavMenu/>
          {children}
          </SessionProvider>
          </body>
    </html>
  );
}
