name: Notification Cron Job

on:
  schedule:
    # Run every 15 minutes
    - cron: '*/15 * * * *'

  # Allow manual triggering
  workflow_dispatch:

jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Notification API
        run: |
          curl -X GET ${{ secrets.APP_URL }}/api/cron/notifications \
          -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}"
